# Generated by Django 4.0.1 on 2022-02-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=30)),
                ('total_rooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('internet', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('Balcony', models.BooleanField(default=False)),
                ('Yard', models.BooleanField(default=False)),
                ('Disabled_Access', models.BooleanField(default=False)),
                ('Garage', models.BooleanField(default=False)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
