# Generated by Django 4.0.1 on 2022-02-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Balcony',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Disabled_Access',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Garage',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Yard',
        ),
        migrations.RemoveField(
            model_name='room',
            name='property_type',
        ),
    ]
