# Generated by Django 4.0.1 on 2022-03-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_room_total_rooms_alter_room_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='poster',
        ),
    ]
