# Generated by Django 4.0.1 on 2022-03-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_room_photo1_room_photo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo2',
        ),
    ]
